### ISSUE TITLE
for some smartphone vendors it will force closed application

### ISSUE THREAD

**Issue by andalasid** [pavzay/flutter_unity_ads#1]
Hei, I found a problem in oppo device. it will close the app when first initial process.

**Comment by pavzay** [comment]
@andalasid Provide more information: plugin version, logs, error info, device info, etc.

**Comment by andalasid** [comment]
Thanks for replaying, I have an issue when release mode on android 6 below. plugin version 0.0.3. issue: Application can't initiate launce or force closed.

**Comment by ahmedthinkdifferent** [comment]
@andalasid  @pavzay i solved this issue and created pull request.

**Comment by pavzay** [comment]
@andalasid check your case on new version of plugin
`unity_ads_plugin: ^0.1.1`
