### ISSUE TITLE
No fill for placement Banner_Android

### ISSUE THREAD

**Issue by Hieuntdz** [pavzay/flutter_unity_ads#15]
hi sir, When use test mode the banner work fine. but when i build product mode (testMode = false) i had error : 
errorMessage: Placement Banner_Android failed to fill!, errorCode: NO_FILL
Is this plugin have this problem. How can i fix this. 
Thank you !

**Comment by pavzay** [comment]
Hi, everything is configured correctly if you see ads in test mode

check comments for more details:
https://github.com/pavzay/flutter_unity_ads/issues/11#issuecomment-890462165
https://forum.unity.com/threads/android-11-unity-ads-was-not-able-to-get-current-network-type-due-to-missing-permission.1087775/#post-7135631
