### ISSUE TITLE
how to detect video ads fil availability 

### ISSUE THREAD

**Issue by sumit-coder** [pavzay/flutter_unity_ads#21]
how to detect video ads fil availability if there is no fill it just does nothing if there is a callback for that would be very helpful because this i am losing money $ plz respond

**Comment by pavzay** [comment]
you can try to use 'failed' callback of load method. it is a new method in 0.3.0 version of unity_ads_plugin

```
UnityAds.load(
  placementId: 'PLACEMENT_ID',
  onComplete: (placementId) => print('Load Complete $placementId'),
  onFailed: (placementId, error, message) {
    print('Load Failed $placementId: $error $message');
    if (error == UnityAdsLoadError.noFill) {
      //do something
    }
  },
);
```

**Comment by sumit-coder** [comment]
Thanks 

> you can try to use 'failed' callback of load method. it is a new method in 0.3.0 version of unity_ads_plugin
> 
> ```
> UnityAds.load(
>   placementId: 'PLACEMENT_ID',
>   onComplete: (placementId) => print('Load Complete $placementId'),
>   onFailed: (placementId, error, message) {
>     print('Load Failed $placementId: $error $message');
>     if (error == UnityAdsLoadError.noFill) {
>       //do something
>     }
>   },
> );
> ```

Thanks
