### ISSUE TITLE
UnityAds.isReady always return false

### ISSUE THREAD

**Issue by nusa10071999** [pavzay/flutter_unity_ads#4]
on  banner ad format UnityAds.isReady always return false on all device.
but for interstitial ad format UnityAds.isReady return false on spesific device, such as Xiaomi Redmi 4A.
whereas at initialization it returns UnityAdState.ready for all ads
can anyone help me?

**Comment by nusa10071999** [comment]
on ads banner format altrought UnityAds.isReady return false, but i try keep show it, and the banner ad format still shows. Unlike the interstitial ad format, it doesn't show when UnityAds.isReady returns false

**Comment by pavzay** [comment]
I checked UnityAds.isReady for banner ads, it works.
Try to check it with test mode 'true'.

**Comment by AzadCoder** [comment]
I have the same problem.
