### ISSUE TITLE
Type cast Error in _UnityBannerAdState._onBannerAdViewCreated

### ISSUE THREAD

**Issue by RR-Reddy** [pavzay/flutter_unity_ads#5]
I am getting below error when running app with **sound null safety** 

**Here is Full error log** 
![Screenshot 2021-05-25 at 9 02 07 AM](https://user-images.githubusercontent.com/32235964/119435611-1a2e6b00-bd38-11eb-8695-705ad3adf67d.png)

**Comment by RR-Reddy** [comment]
@pavzay

**Comment by RR-Reddy** [comment]
@pavzay  here is pull requet #6

**Comment by pavzay** [comment]
this problem is fixed in 0.2.2 version
